# sociounido-gateway/docker-compose.yml
version: '3.8'

services:
  krakend:
    image: krakend:latest
    container_name: sociounido_gateway
    env_file:
      - .env
    environment:
      - FC_ENABLE=1
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "${API_PORT}:8080"
    networks:
      - sociounido_net

  ms-core:
    build: ../microservicio-club
    container_name: sociounido_ms_core_integ
    networks:
      - sociounido_net

networks:
  sociounido_net:
    driver: bridge